version: '3.9'
services:
  climate_browser:
    build:
      context: .
      dockerfile: Dockerfile
    image: climate_browser
    container_name: climate_browser
    restart: always
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    volumes:
      - .:/app
